
# # Loads packages

  invisible(require(shiny))
  invisible(require(shinydashboard))
  invisible(require(RColorBrewer))
  invisible(require(flexdashboard))
  invisible(require(httr))
  invisible(require(dplyr))
  invisible(require(jsonlite))
  invisible(require(ggplot2))
  invisible(require(knitr))
  invisible(require(lubridate))
  invisible(require(readxl))
  invisible(require(writexl))
  invisible(require(DT))
  invisible(require(mongolite))
  invisible(require(stringr))
  invisible(require(janitor))
  invisible(require(Hmisc))
  invisible(require(dygraphs))
  invisible(require(scales))
  invisible(require(reshape2))
  invisible(require(wordcloud))
  invisible(require(syuzhet))
  invisible(require(stopwords))
  invisible(require(quanteda))
  invisible(require(leaflet))
  invisible(require(tm))
  invisible(require(bayesboot))
  invisible(require(ggpubr))
  invisible(require(shinyjs))
  invisible(require(shinythemes))
  invisible(require(tidyr))
  invisible(require(plotly))

